/*
===============================================================================
                                                                        W1OUT.C
                                                             Output coordinates
===============================================================================
*/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "r1dim.h"

extern float x[],y[],z[],x_1[],y_1[],z_1[];
extern float xko[][DIM1+1],yko[][DIM1+1],zko[][DIM1+1];
extern float xao[][DIM1+1],yao[][DIM1+1],zao[][DIM1+1];
extern float cmao[][4],cmbo[][4],cmbbo[][4],cmo[][4];
extern float rmsda[],rmsdb[],tmsa[],tmsb[];                            /* TB */
extern int   atmnbr[][2],rnber[][2];
extern int   seqa[],seqb[],cova[],covb[];                              /* TB */
extern char  atmnam[][2][4],resnam[][2][4];
extern char  tna[][20],tnb[][20],amode[];                              /* TB */
extern FILE  *fopen(),*fout;

void w1out(char *mode,char *fmatch,char *sejo,char *imol,int num,int *energy,
           int *clusl,char *name_a,char *name_b,char *fna,char *fnb,char *cha,
           char *chb,int npa,int npb,int *us)
{
double value;
int   i,im,im1,in,ii,ten,dc,sn;
char  pdbn[900],*work;

      for (im=1; im<=num; im++)
        {
/*------------------------------------------------------------ Open PDB file */
         if ((sejo[0]=='s')||((sejo[0]=='j')&&(im==1)))
           {
            in=strlen(fmatch); ii=-1;
            for (i=0;i<in-4;i++) { pdbn[++ii]=fmatch[i]; }
            pdbn[++ii]='_';
            value=(double)im; ten=10;work=ecvt(value,ten,&dc,&sn);
            for (i=0;i<dc;i++) { pdbn[++ii]=work[i];}
            if ((sejo[0]=='j')&&(im==1))
              {
               pdbn[++ii]='-';
               value=(double)num; ten=10;work=ecvt(value,ten,&dc,&sn);
               for (i=0;i<dc;i++) { pdbn[++ii]=work[i];}
              }
            pdbn[++ii]='.';pdbn[++ii]='p';pdbn[++ii]='d';
            pdbn[++ii]='b';pdbn[++ii]='\0';
            fout=fopen(pdbn,"w");
/*--------------------------------------------------------- Write PDB header */
            fprintf(fout,"REMARK  Complex: %s (%s, %s) - %s (%s, %s)",
                    name_a,fna,cha,name_b,fnb,chb);
            fprintf(fout,"\nREMARK  Generated by GRAMM"); 
            fprintf(fout,"\nREMARK");
            if (imol[0]=='y')
              {
               fprintf(fout,"\nREMARK  Chain R: %s  ",name_a);
               fprintf(fout,"(initial coordinates)");
               fprintf(fout,"\nREMARK  Chain L: %s  ",name_b);
               fprintf(fout,"(initial coordinates)");
              }
            fprintf(fout,"\nREMARK  Chain A: %s  ",name_a);
            fprintf(fout,"\nREMARK  Chain B: %s  ",name_b);
            if (mode[0]=='t') {
              fprintf(fout,"\nREMARK                   templates         ");
              if (amode[0]=='i') fprintf(fout,"  ");
              fprintf(fout,"tm-score     rmsd     seq-id   coverage"); }
           }
         if (sejo[0]=='s')
           {
            fprintf(fout,"\nREMARK  Model %4d",im);

            if (mode[0]=='f') {
               fprintf(fout,"  energy= %4d  cluster-lowres= %3d",
                       energy[im],clusl[im]); }
            if (mode[0]=='t') {
               fprintf(fout,"  %s %s  %4.2f %4.2f  %4.1f %4.1f",
                       tna[im],tnb[im],tmsa[im],tmsb[im],rmsda[im],rmsdb[im]);
               fprintf(fout,"  %3d %3d  %3d %3d",
                       seqa[im],seqb[im],cova[im],covb[im]); }
            fprintf(fout,"\nREMARK");
           }
         if ((sejo[0]=='j')&&(im==1)) 
           {
            for (im1=1; im1<=num; im1++)
              {
               fprintf(fout,"\nREMARK  Model %4d",im1);
               if (mode[0]=='f') {
                  fprintf(fout,"  energy= %4d  cluster-lowres= %3d",
                          energy[im1],clusl[im1]); }
               if (mode[0]=='t') {
                  fprintf(fout,"  %s %s  %4.2f %4.2f  %4.1f %4.1f",tna[im1],
                          tnb[im1],tmsa[im1],tmsb[im1],rmsda[im1],rmsdb[im1]);
                  fprintf(fout,"  %3d %3d  %3d %3d",
                          seqa[im1],seqb[im1],cova[im1],covb[im1]); }
              }
            fprintf(fout,"\nREMARK");
           }
/*------------------------------------------------------------ Initial mol.A */
         if((imol[0]=='y')&&((sejo[0]=='s')||((sejo[0]=='j')&&(im==1))))
           {
           for (i=1; i<=npa; i++)
	         {
              fprintf(fout,"\nATOM  %5d %c%c%c%c%c%c%c%c R%4d",
                      atmnbr[i][0],
                      atmnam[i][0][0],atmnam[i][0][1],
                      atmnam[i][0][2],atmnam[i][0][3],
                      resnam[i][0][0],resnam[i][0][1],
                      resnam[i][0][2],resnam[i][0][3],
                      rnber[i][0]);
              fprintf(fout,"    %8.3f%8.3f%8.3f",
                      x_1[i],y_1[i],z_1[i]);
              }
/*          if (us[42])
              {
               fprintf(fout,"\nATOM      1  M   CMS R   0    ");
               fprintf(fout,"%8.3f%8.3f%8.3f",
                       cmao[im][1],cmao[im][2],cmao[im][3]);
              } */
            fprintf(fout,"\nTER");
/*------------------------------------------------------------ Initial mol.B */

            for (i=1; i<=npb; i++)
	          {
               fprintf(fout,"\nATOM  %5d %c%c%c%c%c%c%c%c L%4d",
                       atmnbr[i][1],
                       atmnam[i][1][0],atmnam[i][1][1],
                       atmnam[i][1][2],atmnam[i][1][3],
                       resnam[i][1][0],resnam[i][1][1],
                       resnam[i][1][2],resnam[i][1][3],
                       rnber[i][1]);
               fprintf(fout,"    %8.3f%8.3f%8.3f",x[i],y[i],z[i]);
              }
            if (us[42])
              {
               fprintf(fout,"\nATOM      1  M   CMS L   0    ");
               if (us[41])fprintf(fout,"%8.3f%8.3f%8.3f",
                                  cmbbo[im][1],cmbbo[im][2],cmbbo[im][3]);
               else       fprintf(fout,"%8.3f%8.3f%8.3f",
                                  cmbo[im][1],cmbo[im][2],cmbo[im][3]);
              }
            fprintf(fout,"\nTER");
           }
/*------------------------------------------------------- Mol.A&B processing */
         fprintf(fout,"\nMODEL %8d",im);

         for (i=1; i<=npa; i++)
	       {
            fprintf(fout,"\nATOM  %5d %c%c%c%c%c%c%c%c A%4d",
                    atmnbr[i][0],
                    atmnam[i][0][0],atmnam[i][0][1],
                    atmnam[i][0][2],atmnam[i][0][3],
                    resnam[i][0][0],resnam[i][0][1],
                    resnam[i][0][2],resnam[i][0][3],
                    rnber[i][0]);
            fprintf(fout,"    %8.3f%8.3f%8.3f",
                    xao[im][i],yao[im][i],zao[im][i]);
           }
/*       if (us[42])
           {
            fprintf(fout,"\nATOM      1  M   CMS A   0    ");
            fprintf(fout,"%8.3f%8.3f%8.3f",
                    cmao[im][1],cmao[im][2],cmao[im][3]);
           } */
         fprintf(fout,"\nTER");

         for (i=1; i<=npb; i++)
	       {
            fprintf(fout,"\nATOM  %5d %c%c%c%c%c%c%c%c B%4d    ",
                    atmnbr[i][1],
                    atmnam[i][1][0],atmnam[i][1][1],
                    atmnam[i][1][2],atmnam[i][1][3],
                    resnam[i][1][0],resnam[i][1][1],
                    resnam[i][1][2],resnam[i][1][3],
                    rnber[i][1]);
            fprintf(fout,"%8.3f%8.3f%8.3f",xko[im][i],yko[im][i],zko[im][i]);
           }
         if (us[42])        /* center of mass for predicted ligand positions */
           {
            fprintf(fout,"\nATOM      1  M   CMS B   0    ");
            fprintf(fout,"%8.3f%8.3f%8.3f",cmo[im][1],cmo[im][2],cmo[im][3]);
           }
         fprintf(fout,"\nTER\nENDMDL");
         if (sejo[0]=='s') fclose(fout);
        }
      if (sejo[0]=='j') fclose(fout);
}
